AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Description: BucketName
    Type: String
    MinLength: '1'
    MaxLength: '2048'
    
Resources:
  TableCas:
    Type: AWS::CloudFormation::Stack
    Properties:
      # TemplateURL: !Sub "https://${BucketName}.s3.amazonaws.com/templates/dynamodb/tableCas.yaml"
      TemplateURL: https://github.com/meracan/aws-cloudformation/blob/master/dynamodb/tableCas.yaml
      Parameters:
        TableName: !Sub "${BucketName}-Cas"
  TableData:
    Type: AWS::CloudFormation::Stack
    Properties:
      # TemplateURL: !Sub "https://${BucketName}.s3.amazonaws.com/templates/dynamodb/tableData.yaml"
      TemplateURL: https://github.com/meracan/aws-cloudformation/blob/master/dynamodb/tableData.yaml
      Parameters:
        TableName: !Sub "${BucketName}-Data"

Outputs:
  TableCas:
    Value: !Ref TableCas
  TableData:
    Value: !Ref TableData